
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tipos_documento (id SERIAL PRIMARY KEY, codigo VARCHAR(10) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS generos (id SERIAL PRIMARY KEY, codigo VARCHAR(10) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS aseguradoras (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre VARCHAR(150) NOT NULL, nit VARCHAR(30), activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS pacientes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tipo_documento_id INTEGER NOT NULL REFERENCES tipos_documento(id), numero_documento VARCHAR(30) UNIQUE NOT NULL, primer_nombre VARCHAR(80) NOT NULL, segundo_nombre VARCHAR(80), primer_apellido VARCHAR(80) NOT NULL, segundo_apellido VARCHAR(80), fecha_nacimiento DATE NOT NULL, genero_id INTEGER NOT NULL REFERENCES generos(id), telefono VARCHAR(40), email VARCHAR(150), direccion TEXT, activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS paciente_aseguradora (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), paciente_id UUID REFERENCES pacientes(id) ON DELETE CASCADE, aseguradora_id UUID REFERENCES aseguradoras(id), numero_afiliacion VARCHAR(80), activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS contactos_emergencia (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), paciente_id UUID REFERENCES pacientes(id) ON DELETE CASCADE, nombre VARCHAR(150) NOT NULL, parentesco VARCHAR(80), telefono VARCHAR(40), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS historias_clinicas (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), paciente_id UUID UNIQUE REFERENCES pacientes(id) ON DELETE CASCADE, numero_historia VARCHAR(50) UNIQUE NOT NULL, estado VARCHAR(30) DEFAULT 'ACTIVA', created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS antecedentes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), historia_id UUID REFERENCES historias_clinicas(id) ON DELETE CASCADE, tipo VARCHAR(80) NOT NULL, descripcion TEXT NOT NULL, registrado_por UUID, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS consentimientos_medicos (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), paciente_id UUID REFERENCES pacientes(id), tipo VARCHAR(100) NOT NULL, descripcion TEXT, aceptado BOOLEAN DEFAULT TRUE, firmado_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS estados_cita (id SERIAL PRIMARY KEY, codigo VARCHAR(30) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS especialidades (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre VARCHAR(120) UNIQUE NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS medicos_referentes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre VARCHAR(150) NOT NULL, email VARCHAR(150), especialidad_id UUID REFERENCES especialidades(id), activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS citas (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), paciente_id UUID REFERENCES pacientes(id), medico_id UUID REFERENCES medicos_referentes(id), especialidad_id UUID REFERENCES especialidades(id), estado_id INTEGER REFERENCES estados_cita(id), fecha_hora TIMESTAMP NOT NULL, motivo TEXT, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS atenciones (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), historia_id UUID REFERENCES historias_clinicas(id), cita_id UUID REFERENCES citas(id), medico_usuario_id UUID, motivo_consulta TEXT, enfermedad_actual TEXT, analisis TEXT, plan_manejo TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS evoluciones_medicas (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), atencion_id UUID REFERENCES atenciones(id) ON DELETE CASCADE, descripcion TEXT NOT NULL, usuario_id UUID, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notas_alta (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), atencion_id UUID REFERENCES atenciones(id), resumen TEXT, recomendaciones TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS diagnosticos_cie10 (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), codigo VARCHAR(20) UNIQUE NOT NULL, nombre TEXT NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS diagnosticos_atencion (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), atencion_id UUID REFERENCES atenciones(id) ON DELETE CASCADE, diagnostico_id UUID REFERENCES diagnosticos_cie10(id), tipo VARCHAR(30) DEFAULT 'PRINCIPAL');
CREATE TABLE IF NOT EXISTS procedimientos_cups (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), codigo VARCHAR(30) UNIQUE NOT NULL, nombre TEXT NOT NULL, tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('LAB','RAD','CLINICO')), activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS procedimientos_atencion (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), atencion_id UUID REFERENCES atenciones(id) ON DELETE CASCADE, procedimiento_id UUID REFERENCES procedimientos_cups(id));
CREATE TABLE IF NOT EXISTS tipos_orden_diagnostica (id SERIAL PRIMARY KEY, codigo VARCHAR(20) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, sistema_destino VARCHAR(10) CHECK (sistema_destino IN ('LIS','RIS')), activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS prioridades_orden (id SERIAL PRIMARY KEY, codigo VARCHAR(20) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS estados_orden (id SERIAL PRIMARY KEY, codigo VARCHAR(40) UNIQUE NOT NULL, nombre VARCHAR(80) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS ordenes_diagnosticas (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), numero_orden VARCHAR(50) UNIQUE NOT NULL, paciente_id UUID REFERENCES pacientes(id), historia_id UUID REFERENCES historias_clinicas(id), atencion_id UUID REFERENCES atenciones(id), tipo_orden_id INTEGER REFERENCES tipos_orden_diagnostica(id), prioridad_id INTEGER REFERENCES prioridades_orden(id), estado_id INTEGER REFERENCES estados_orden(id), sistema_destino VARCHAR(10) CHECK (sistema_destino IN ('LIS','RIS')), observaciones TEXT, creado_por UUID, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS detalle_orden (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), orden_id UUID REFERENCES ordenes_diagnosticas(id) ON DELETE CASCADE, procedimiento_id UUID REFERENCES procedimientos_cups(id), cantidad INTEGER DEFAULT 1, observacion TEXT);
CREATE TABLE IF NOT EXISTS sistemas_integracion (id SERIAL PRIMARY KEY, codigo VARCHAR(10) UNIQUE NOT NULL, nombre VARCHAR(100) NOT NULL, endpoint_base TEXT NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS integraciones (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), orden_id UUID REFERENCES ordenes_diagnosticas(id), sistema_destino VARCHAR(10) CHECK (sistema_destino IN ('LIS','RIS')), endpoint TEXT, estado VARCHAR(30) DEFAULT 'PENDIENTE', external_order_id UUID, payload_json JSONB, response_json JSONB, intentos INTEGER DEFAULT 0, ultimo_error TEXT, enviado_at TIMESTAMP, confirmado_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS resultados_diagnosticos (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), orden_id UUID REFERENCES ordenes_diagnosticas(id), sistema_origen VARCHAR(10) CHECK (sistema_origen IN ('LIS','RIS')), tipo_resultado VARCHAR(40) NOT NULL, resumen TEXT, url_documento TEXT, referencia_externa VARCHAR(150), resultado_json JSONB, validado_por VARCHAR(150), fecha_validacion TIMESTAMP, recibido_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notificaciones (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), usuario_id UUID, paciente_id UUID REFERENCES pacientes(id), orden_id UUID REFERENCES ordenes_diagnosticas(id), titulo VARCHAR(150) NOT NULL, mensaje TEXT NOT NULL, leida BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS his_menus (id SERIAL PRIMARY KEY, texto VARCHAR(80) NOT NULL, ruta VARCHAR(120) NOT NULL, icono_bootstrap VARCHAR(80), permiso_requerido VARCHAR(100), orden INTEGER DEFAULT 0, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS auditoria_his (id BIGSERIAL PRIMARY KEY, usuario_id UUID, usuario_email VARCHAR(150), accion VARCHAR(100) NOT NULL, entidad VARCHAR(80), entidad_id UUID, ip VARCHAR(80), user_agent TEXT, detalle TEXT, created_at TIMESTAMP DEFAULT NOW());

CREATE INDEX IF NOT EXISTS idx_pacientes_doc ON pacientes(numero_documento);
CREATE INDEX IF NOT EXISTS idx_ordenes_paciente ON ordenes_diagnosticas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_resultados_orden ON resultados_diagnosticos(orden_id);
