const express = require("express");
const c = require("../controllers/risController");
const p = require("../middlewares/requirePermission");
const r = express.Router();
r.get("/", p("RIS_ACCESS"), c.dashboard);
r.get("/ordenes", p("RIS_ACCESS"), c.orders);
r.get("/agenda", p("RIS_AGENDA"), c.agenda);
r.get("/agenda/crear", p("RIS_AGENDA"), c.agendaCreate);
r.post("/agenda", p("RIS_AGENDA"), c.agendaStore);
r.get("/ejecucion", p("RIS_EXECUTION"), c.execution);
r.post("/estudios/:id/ejecutar", p("RIS_EXECUTION"), c.executeStudy);
r.get("/estudios", p("RIS_ACCESS"), c.studies);
r.get("/estudios/:id", p("RIS_ACCESS"), c.studyShow);
r.post("/estudios/:id/pacs", p("RIS_PACS"), c.linkPacs);
r.get("/orthanc/find", p("RIS_PACS"), c.orthancFindForm);
r.post("/orthanc/find", p("RIS_PACS"), c.orthancFind);
r.get("/pacs", (req, res) => res.redirect("/orthanc/find"));
r.get("/informes", p("RIS_REPORTS"), c.reports);
r.get("/informes/estudio/:id", p("RIS_REPORTS"), c.reportForm);
r.post("/informes/estudio/:id", p("RIS_REPORTS"), c.saveReport);
r.get("/informes/:id/validar", p("RIS_VALIDATE"), c.validationShow);
r.post("/informes/:id/validar-enviar", p("RIS_SEND_HIS"), c.validateAndSend);
r.get("/pacientes", p("RIS_ACCESS"), c.patients);
r.get("/pacientes/:id/historial", p("RIS_ACCESS"), c.patientHistory);
r.get("/auditoria", p("RIS_AUDIT"), c.audit);
module.exports = r;
