const express = require("express");
const c = require("../controllers/lisController");
const p = require("../middlewares/requirePermission");
const r = express.Router();
r.get("/", p("LIS_ACCESS"), c.dashboard);
r.get("/ordenes", p("LIS_ORDERS"), c.orders);
r.get("/ordenes/:id", p("LIS_ORDERS"), c.orderShow);
r.post("/ordenes/:id/tomar-muestra", p("LIS_SAMPLES"), c.collect);
r.get("/muestras", p("LIS_SAMPLES"), c.samples);
r.get("/resultados", p("LIS_RESULTS"), c.resultsIndex);
r.get("/resultados/:id", p("LIS_RESULTS"), c.resultForm);
r.post("/resultados/:id", p("LIS_RESULTS"), c.saveResults);
r.get("/validacion", p("LIS_VALIDATE"), c.validations);
r.get("/validaciones", p("LIS_VALIDATE"), c.validations);
r.get("/validaciones/:id", p("LIS_VALIDATE"), c.validationShow);
r.post("/validaciones/:id/enviar-his", p("LIS_SEND_HIS"), c.validateAndSend);
r.get("/reportes", p("LIS_RESULTS"), c.reports);
r.get("/reportes/:id", p("LIS_RESULTS"), c.report);
r.get("/pacientes", p("LIS_RESULTS"), c.patients);
r.get("/pacientes/:id/historial", p("LIS_RESULTS"), c.patientHistory);
r.get("/auditoria", p("LIS_AUDIT"), c.audit);
module.exports = r;
